### PR TITLE
Update r2d2m2cp.py

### LINKED ISSUE #244: Possibly Non-optimal parameterization for phi in R2D2M2CP prior
The parameterization of a default phi concentration is getting worse with number of dimensions, leading to multimodal default prior. Replacing the default with just ones, would not make the prior multimodal.

https://github.com/pymc-devs/pymc-experimental/blob/3444ede907abe415251f8ba28c70b670aa94c9f9/pymc_experimental/distributions/multivariate/r2d2m2cp.py#L196

Let's change the default? It should not be too late since it is experimental and anyway subject to change.

### PR DESCRIPTION
**Pull request by ferrine**
close #244

### CODE REVIEW

**Review by ricardoV94 — APPROVED** [review]

**Comment by ferrine** [comment]
What is wrong with numpy?

**Comment by ferrine** [comment]
```
ERROR pymc_experimental/tests/statespace/test_representation.py - DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
```
this seems to be completely unrelated

**Comment by twiecki** [comment]
> ```
> ERROR pymc_experimental/tests/statespace/test_representation.py - DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
> ```
> 
> this seems to be completely unrelated

Fixed by https://github.com/pymc-devs/pymc-experimental/pull/251

**Comment by jessegrabowski** [comment]
CI should pass now if you merge the latest main into your branch

**Comment by ferrine** [comment]
back here to check PR again

**Pull request merged**
