### PR TITLE
Move `tests/` to project root

### LINKED ISSUE #351: Move `tests` to project root
It's currently inside the source folder, so it gets distributed via pip. IMO it's cleaner to keep the two separate.

### PR DESCRIPTION
**Pull request by jessegrabowski**
Closes #351

### CODE REVIEW

**Comment by maresb** [comment]
The branch is all screwed up, but I like the proposal.

**Comment by jessegrabowski** [comment]
I'm not sure why it's showing merge conflicts. Rebasing my local branch onto main does nothing, so things should be aligned?

**Comment by maresb** [comment]
Hmm, does `git fetch upstream main:main` pull anything for you?

**Comment by jessegrabowski** [comment]
I just updated main, did `git reset --hard origin/main` on my branch, force pushed, then moved the test files and committed. This was my nuclear attack; I am officially defeated by these merge conflicts.

**Comment by jessegrabowski** [comment]
Also I can locally merge my branch into main without conflicts. So I'm really stumped.

**Comment by jessegrabowski** [comment]
The only way nuclear attack can fail is if you don't attack enough.

**Review by maresb — APPROVED** [review]
Nice!

**Comment by jessegrabowski** [comment]
Do you know why the old CI runners haven't gone away? I edited `.github/tests.yml` to point to the right place

**Comment by maresb** [comment]
Ah. I think it's the way the tests are referenced in the branch rules. Probably @ricardoV94 will need to remove and readd the required tests due to the label change.

**Comment by ricardoV94** [comment]
> Ah. I think it's the way the tests are referenced in the branch rules. Probably @ricardoV94 will need to remove and readd the required tests due to the label change.

Right, I'll do that

**Comment by ricardoV94** [comment]
Done

**Pull request merged**
