### PR TITLE
add default to argument to prior util

### PR DESCRIPTION
**Pull request by ferrine**

### CODE REVIEW

**Comment by ricardoV94** [comment]
What's the point of calling this function with an empty model?

**Comment by ferrine** [comment]
> What's the point of calling this function with an empty model?

if you pass everything to kwargs for example

**Comment by ricardoV94** [comment]
Will this function ever do anything with empty var_names?

**Comment by ferrine** [comment]
> Will this function ever do anything with empty var_names?

kwargs + var_names combined matter, not just var_names

**Comment by ferrine** [comment]
> > > Will this function ever do anything with empty var_names?
> > 
> > 
> > kwargs + var_names combined matter, not just var_names
> 
> So why this change to allow kwargs + no var_names? If that case can only end up with an empty dictionary?

he change is required to use the function with kwargs only

**Review by ricardoV94 — APPROVED** [review]

**Pull request merged**
