### PR TITLE
Update for PyMC v5.11

### PR DESCRIPTION
**Pull request by zaxtax**
This should let `pymc-experimental` build with pymc v5.11.

This relates to #317

### CODE REVIEW

**Comment by ricardoV94** [comment]
@zaxtax you also need to update the versions here: https://github.com/pymc-devs/pymc-experimental/tree/main/conda-envs

**Comment by ricardoV94** [comment]
Tests are failing because `moment` is still being used internally?

**Comment by zaxtax** [comment]
It seems to fail locally for me as well.

**Comment by ricardoV94** [comment]
> You need to replace these methods as well:
> 
> https://github.com/pymc-devs/pymc-experimental/blob/ee07caa259517c14697e285f5029c1cca076d1b9/pymc_experimental/distributions/continuous.py#L214

I just picked one, I think there are more

**Comment by zaxtax** [comment]
Oh weird grep wasn't finding that for me for some reason

**Comment by zaxtax** [comment]
The current errors since unrelated to moment but happy to fix them.

**Review by ricardoV94 — APPROVED** [review]

**Pull request merged**
