### PR TITLE
Histogram trick

### PR DESCRIPTION
**Pull request by ferrine**
Add histogram trick to experimental utils. The idea is to reduce computations for huge data with smart preprocessing

Features:
- [x] Dask
- [x] Zero inflation
- [x] Discrete data
- [x] Continuous data
- [x] Docs
- [x] 2d inputs

```python
big_data = np.random.randn(10000000000)  # can be dask array as well
```

<table>
  <tr>
    <td>Before</td><td>After</td>
  </tr>
  <tr>
   <td>
<pre>
with pm.Model():
    m = pm.Normal("m")
    s = pm.HalfNormal("s")
    a = pm.Normal("obs", m, s, observed=big_data)
    trace = pm.sample() # very slow
</pre>
   </td>
<td>
<pre>
with pm.Model():
    m = pm.Normal("m")
    s = pm.HalfNormal("s")
    pot = pmx.distributions.histogram_approximation(
        "histogram_potential",
        pm.Normal.dist(m, s),
        observed=big_data,
        n_quantiles=1000
    )
    trace = pm.sample() # very fast
</pre>
</td>
  </tr>
</table>
And Discrete distributions

```python
big_data = np.random.randint(0, 10000, size=10000000000)  # can be dask array as well
```

<table>
  <tr>
    <td>Before</td><td>After</td>
  </tr>
  <tr>
   <td>
<pre>
with pm.Model():
    lam = pm.Exponential("lambda")
    a = pm.Poisson("obs", lam, observed=big_data)
    trace = pm.sample() # very slow
</pre>
   </td>
<td>
<pre>
with pm.Model():
    lam = pm.Exponential("lambda")
    pot = pmx.distributions.histogram_approximation(
        "histogram_potential",
        pm.Poisson.dist(m, s),
        observed=big_data,
        min_count=1000
    )
    trace = pm.sample() # very fast
</pre>
</td>
  </tr>
</table>

### CODE REVIEW

**Comment by ricardoV94** [comment]
Can we come up with a better name than `trick`? Approximation, Compression, Discretization?

**Comment by ferrine** [comment]
> Can we come up with a better name than `trick`? Approximation, Compression, Discretization?

Don't know, I just like the "trick"

**Comment by ferrine** [comment]
"approximation" is not that fancy

**Comment by ricardoV94** [comment]
Looks like we need a pre-commit hook. There's a missing empty line at the end of one of the files

**Comment by twiecki** [comment]
I agree with @ricardoV94, `approximation` is more appropriate here. We can leave the fancy language for the blog post @ferrine ;).

**Comment by ferrine** [comment]
Ok, I'll will take that in account!

**Comment by ferrine** [comment]
I seem to have finished the implementation for the histogram approximation. I converged with the following API
1. Moved `histogram_utils` to `pmx.distributions`.
2. `histogram_utils` contain the code used to approximate a potential. Namely, `pmx.distributions.histogram_approximation`
3. See the detailed API in the PR description

**Comment by ferrine** [comment]
blocked by #44

**Comment by ferrine** [comment]
The PR is ready for review

**Review by aloctavodia — APPROVED** [review]
LGTM!

**Pull request merged**
