### PR TITLE
Handle latest PyMC/PyTensor breaking changes

### PR DESCRIPTION
**Pull request by ricardoV94**

### CODE REVIEW

**Review by twiecki — APPROVED** [review]

**Comment by ricardoV94** [comment]
Still some broken stuff, but almost done

**Comment by ricardoV94** [comment]
Ok 4 failing tests, one marginal, two smc, and one statespace.

@jessegrabowski: FAILED pymc_experimental/tests/statespace/test_VARMAX.py::test_impulse_response[scalar_shock_size] - ValueError: initial_shock has 0 dims but 1 dim labels were provided.

**Comment by jessegrabowski** [comment]
Should be fixed by #346

**Comment by ricardoV94** [comment]
@jessegrabowski can we fix just the dim here? Otherwise this PR depends on that and that one will depend on this, unless you put all commits from this PR there?

**Comment by jessegrabowski** [comment]
Sure np

**Comment by ricardoV94** [comment]
> Sure np

Can you push or tell me what to change. If it's convoluted I can also just mark it as xfail?

**Comment by jessegrabowski** [comment]
I'm doing it now, give me about an hour

**Comment by ricardoV94** [comment]
> I'm doing it now, give me about an hour

Counting

**Comment by ricardoV94** [comment]
One marginal test and two SMC tests

**Comment by ciguaran** [comment]
@ricardoV94 hei! could you share the version of blackjax you are using? most likely you can fix it by replacing '`blackjax.smc.adaptive_tempered'` with `blackjax.adaptive_tempered_smc`

**Comment by ricardoV94** [comment]
@ciguaran other stuff is failing downstream after I update the function path. I'll mark it as xfail for now

**Comment by ricardoV94** [comment]
To unblock parallel work I marked two tests as xfail and opened issues for it
#355 
#354

**Comment by jessegrabowski** [comment]
Is this ready to merge?

**Comment by zaxtax** [comment]
We should bump the middle version number as part of this change

**Pull request merged**
